
# Define Variable
variables:
  BUILD_IMAGE: docker:dind
  ENV_FILE: $ENV_FILE_KTS_BACKEND

before_script:
  - echo "$ENV_FILE_KTS_BACKEND" > .env

stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - dev
    - main
  tags:
    - ubuntu
  script:
    - docker login -u mtk246 -p mtkMTK123#
    - docker build . --file Dockerfile --tag mtk246/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
    - docker push mtk246/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
    - docker volume prune -f && docker builder prune -a -f && docker image prune -a -f

deploy-job:
  stage: deploy
  image: docker/compose
  only:
    - dev
    - main
  tags:
    - ubuntu
  script:
    - docker login -u mtk246 -p mtkMTK123#
    - docker-compose --project-name=$CI_PROJECT_NAME:$CI_COMMIT_BRANCH -f docker-compose.yml up -d
    - docker volume prune -f && docker builder prune -f && docker image prune -a -f