version: '3.3'

services:
  service:
    image: "mtk246/${{ github.event.repository.name}}:${{ github.ref_name }}"
    container_name: "${{ github.event.repository.name}}-${{ github.ref_name }}"
    networks:
      - server
    ports:
      - 8002:8000
    restart: always

networks:
  server:
    external: true
