name: CI Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Build Docker Image
        run: |
          docker build -t my-image .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
