name: CI Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version || echo "docker-compose not installed"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up environment variables
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create external network
        run: |
          docker network create server || echo "Network 'server' already exists"

      - name: Build Docker Image
        run: |
          docker build -t mtk246/${{ env.REPO_NAME }}:${{ env.REF_NAME }} .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
