name: CI Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Build Docker Image
        run: |
          docker build -t mtk246/${{ github.event.repository.name }}:${{ github.ref_name }} .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
