name: Docker Compose Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker (optional if Docker is pre-installed and configured on the runner)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Create an .env file (optional, based on your variables)
      - name: Create .env file
        run: |
          echo "CI_PROJECT_NAME=${{ github.event.repository.name }}" >> .env
          echo "CI_COMMIT_BRANCH=${{ github.ref_name }}" >> .env

      # Step 4: Run Docker Compose
      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml down || true
          docker-compose -f ./docker-compose.yml up -d
