name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mtk246/${{ github.event.repository.name }}:${{ github.sha }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push mtk246/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Set up Tailscale VPN
        run: |
          curl -fsSL "https://pkgs.tailscale.com/stable/ubuntu/gpg" | sudo tee /etc/apt/trusted.gpg.d/tailscale.asc
          echo "deb https://pkgs.tailscale.com/stable/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install -y tailscale
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-actions

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            # Ensure Docker and Docker Compose are installed on the server
            docker-compose pull
            docker-compose up -d
