name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # Step 2: Create an .env file (optional, based on your variables)
      - name: Create .env file
        run: |
          echo "CI_PROJECT_NAME=${{ github.event.repository.name }}" >> .env
          echo "CI_COMMIT_BRANCH=${{ github.ref_name }}" >> .env

      # Step 3: SSH to server and deploy
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/dev/bee-express-admin-backend
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

          # Set environment variables
            echo "REPO_NAME=${{ github.event.repository.name }}" > .env
            echo "REF_NAME=${{ github.ref_name }}" >> .env

          # Build the Docker image locally
            docker build -t mtk246/${{ github.event.repository.name }}:${{ github.ref_name }} .

            docker-compose --env-file .env down || true
            docker-compose --env-file .env up -d
